import { useMemo } from 'react';
import { FlaskConical } from 'lucide-react';
import type { ApiResponse, ApiRequest } from '../../api/apiTester';
import type { Assertion } from '../../services/apiTesterStorage';

interface AutoGeneratedTestGeneratorProps {
  response: ApiResponse | null;
  request?: ApiRequest;
  onGenerateTests?: (assertions: Assertion[]) => void;
}

const AutoGeneratedTestGenerator = ({ response, request, onGenerateTests }: AutoGeneratedTestGeneratorProps) => {
  // Helper function to validate dates
  const isValidDate = (dateString: string): boolean => {
    // Check for common date formats
    const datePatterns = [
      /^\d{4}-\d{2}-\d{2}$/, // YYYY-MM-DD
      /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/, // ISO datetime
      /^\d{1,2}\/\d{1,2}\/\d{4}/, // MM/DD/YYYY
      /^\d{1,2}-\d{1,2}-\d{4}/ // MM-DD-YYYY
    ];
    
    return datePatterns.some(pattern => pattern.test(dateString)) && 
           !isNaN(new Date(dateString).getTime());
  };

  // Helper function to validate emails
  const isValidEmail = (email: string): boolean => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  };

  // Memoized function to analyze response and generate comprehensive tests
  const generatedAssertions = useMemo((): Assertion[] => {
    if (!response) return [];
    
    const assertions: Assertion[] = [];
    
    // Always test status code
    assertions.push({ type: 'status', op: 'equals', value: response.status });
    
    // Test content type header
    const headersLc = Object.fromEntries(
      Object.entries(response.headers || {}).map(([k, v]) => [k.toLowerCase(), String(v)])
    );
    const ct = headersLc['content-type'];
    if (ct) {
      const mime = ct.split(';')[0].trim();
      assertions.push({ type: 'header', key: 'Content-Type', op: 'contains', value: mime });
    }
    
    // Analyze response data to generate comprehensive tests
    const data = typeof response.data === 'string' ? 
      (() => { try { return JSON.parse(response.data); } catch { return response.data; } })() : 
      response.data;
    
    if (data && typeof data === 'object' && !Array.isArray(data)) {
      // For object responses, generate tests for each property
      Object.keys(data).forEach((key) => {
        const value = data[key];
        
        // Always test that the property exists
        assertions.push({ type: 'json', path: key, op: 'exists' });
        
        // Generate type-specific tests
        if (value !== null && value !== undefined) {
          if (Array.isArray(value)) {
            // For arrays, test length and element structure
            assertions.push({ type: 'json', path: `${key}.length`, op: 'greaterThan', value: -1 });
            
            // If array has elements, analyze first few for patterns
            if (value.length > 0 && typeof value[0] === 'object' && value[0] !== null) {
              Object.keys(value[0]).forEach(nestedKey => {
                assertions.push({ type: 'json', path: `${key}[0].${nestedKey}`, op: 'exists' });
                
                // Add value-based tests for common patterns
                const firstValue = value[0][nestedKey];
                if (typeof firstValue === 'string') {
                  if (isValidDate(firstValue)) {
                    assertions.push({ type: 'json', path: `${key}[*].${nestedKey}`, op: 'matches', value: '\\d{4}-\\d{2}-\\d{2}' });
                  } else if (isValidEmail(firstValue)) {
                    assertions.push({ type: 'json', path: `${key}[*].${nestedKey}`, op: 'matches', value: '^[^@]+@[^@]+\\.[^@]+$' });
                  }
                } else if (typeof firstValue === 'number' && firstValue >= 0) {
                  assertions.push({ type: 'json', path: `${key}[*].${nestedKey}`, op: 'greaterThan', value: -1 });
                }
              });
            }
          } else if (typeof value === 'object') {
            // For nested objects, test structure
            Object.keys(value).forEach(nestedKey => {
              assertions.push({ type: 'json', path: `${key}.${nestedKey}`, op: 'exists' });
            });
          } else {
            // For primitive values, add value-based tests
            if (typeof value === 'string') {
              if (isValidDate(value)) {
                assertions.push({ type: 'json', path: key, op: 'matches', value: '\\d{4}-\\d{2}-\\d{2}' });
              } else if (isValidEmail(value)) {
                assertions.push({ type: 'json', path: key, op: 'matches', value: '^[^@]+@[^@]+\\.[^@]+$' });
              }
            } else if (typeof value === 'number' && value >= 0) {
              assertions.push({ type: 'json', path: key, op: 'greaterThan', value: -1 });
            }
          }
        }
      });
    } else if (Array.isArray(data)) {
      // For array responses, test array properties
      assertions.push({ type: 'json', path: 'length', op: 'greaterThan', value: -1 });
      
      // If array has elements, analyze structure
      if (data.length > 0) {
        const firstItem = data[0];
        if (firstItem && typeof firstItem === 'object') {
          Object.keys(firstItem).forEach((key) => {
            assertions.push({ type: 'json', path: `[0].${key}`, op: 'exists' });
            
            // Add pattern-based tests
            const value = firstItem[key];
            if (typeof value === 'string' && value.length > 0) {
              if (isValidDate(value)) {
                assertions.push({ type: 'json', path: `[*].${key}`, op: 'matches', value: '\\d{4}-\\d{2}-\\d{2}' });
              } else if (isValidEmail(value)) {
                assertions.push({ type: 'json', path: `[*].${key}`, op: 'matches', value: '^[^@]+@[^@]+\\.[^@]+$' });
              }
            } else if (typeof value === 'number' && value >= 0) {
              assertions.push({ type: 'json', path: `[*].${key}`, op: 'greaterThan', value: -1 });
            }
          });
        }
      }
    }
    
    return assertions;
  }, [response]);
  
  const handleGenerateTests = () => {
    if (onGenerateTests && response) {
      onGenerateTests(generatedAssertions);
    }
  };

  return (
    <button
      onClick={handleGenerateTests}
      className="flex items-center gap-1.5 px-3.5 py-2.5 bg-white/60 dark:bg-slate-800/60 backdrop-blur-sm border border-gray-200/60 dark:border-slate-700/60 text-gray-700 dark:text-gray-300 rounded-xl hover:bg-emerald-100/60 dark:hover:bg-emerald-900/40 transition-all duration-200"
      title="Generate comprehensive tests from response structure"
      disabled={!response}
    >
      <FlaskConical className="w-4 h-4" />
      {generatedAssertions.length > 0 ? `Gen ${generatedAssertions.length} Tests` : 'Generate Tests'}
    </button>
  );
};

export default AutoGeneratedTestGenerator;