import type { TestCase, TestSuite } from '../../../services/apiTesterStorage';

// Environment configuration for matrix testing
export interface TestEnvironment {
  name: string;
  baseUrl: string;
  variables: Record<string, string>;
}

// Generate GitHub Actions workflow YAML
export function generateGitHubActionsWorkflow(
  tests: TestCase[],
  options: {
    name?: string;
    schedule?: string; // cron expression
    environments?: TestEnvironment[];
    nodeVersion?: string;
  } = {}
): string {
  const {
    name = 'API Tests',
    schedule,
    environments = [],
    nodeVersion = '18'
  } = options;

  const hasMatrix = environments.length > 1;

  let workflow = `name: ${name}

on:
  workflow_dispatch:
${schedule ? `  schedule:
    - cron: '${schedule}'
` : ''}
jobs:
  test:
    runs-on: ubuntu-latest
${hasMatrix ? `    strategy:
      matrix:
        environment: [${environments.map(e => `'${e.name}'`).join(', ')}]
` : ''}
    steps:
      - name: Run API Tests
        run: |
${generateShellTestCommands(tests, hasMatrix ? '          ' : '          ', hasMatrix)}
`;

  return workflow;
}

// Generate shell script for CLI execution
export function generateShellScript(
  tests: TestCase[],
  options: {
    baseUrl?: string;
    variables?: Record<string, string>;
  } = {}
): string {
  const { baseUrl, variables = {} } = options;

  let script = `#!/bin/bash
# API Test Script
# Generated by KumoDB API Tester

set -e

# Color codes
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

PASSED=0
FAILED=0
TOTAL=${tests.length}

echo "Running $TOTAL API tests..."
echo ""

`;

  // Add variable exports
  if (Object.keys(variables).length > 0) {
    script += '# Environment variables\n';
    for (const [key, value] of Object.entries(variables)) {
      script += `export ${key}="${value}"\n`;
    }
    script += '\n';
  }

  // Add test commands
  tests.forEach((test, index) => {
    const url = baseUrl ? test.request.url.replace(/^https?:\/\/[^\/]+/, baseUrl) : test.request.url;

    script += `# Test ${index + 1}: ${test.name}
echo -n "Test ${index + 1}/${tests.length}: ${test.name}... "
RESPONSE=$(curl -s -w "\\n%{http_code}" -X ${test.request.method} "${url}"`;

    // Add headers
    if (test.request.headers) {
      for (const [key, value] of Object.entries(test.request.headers)) {
        script += ` \\\n  -H "${key}: ${value}"`;
      }
    }

    // Add body
    if (test.request.body) {
      const escapedBody = test.request.body.replace(/"/g, '\\"').replace(/\n/g, '\\n');
      script += ` \\\n  -d "${escapedBody}"`;
    }

    script += `)

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$ d')

`;

    // Add basic status check
    script += `if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
  echo -e "\${GREEN}PASSED\${NC} ($HTTP_CODE)"
  ((PASSED++))
else
  echo -e "\${RED}FAILED\${NC} ($HTTP_CODE)"
  ((FAILED++))
fi

`;
  });

  // Add summary
  script += `# Summary
echo ""
echo "========================================="
echo "Test Results: $PASSED passed, $FAILED failed"
if [ $FAILED -eq 0 ]; then
  echo -e "\${GREEN}All tests passed!\${NC}"
  exit 0
else
  echo -e "\${RED}Some tests failed!\${NC}"
  exit 1
fi
`;

  return script;
}

// Generate Node.js test script
export function generateNodeScript(
  tests: TestCase[],
  options: {
    baseUrl?: string;
    variables?: Record<string, string>;
  } = {}
): string {
  const { baseUrl, variables = {} } = options;

  let script = `/**
 * API Test Script
 * Generated by KumoDB API Tester
 *
 * Run with: node test-script.js
 * Or with environment: BASE_URL=https://staging.api.com node test-script.js
 */

const https = require('https');
const http = require('http');

// Configuration
const config = {
  baseUrl: process.env.BASE_URL || '${baseUrl || ''}',
  variables: ${JSON.stringify(variables, null, 4).replace(/\n/g, '\n  ')}
};

// Test definitions
const tests = ${JSON.stringify(tests.map(t => ({
  name: t.name,
  method: t.request.method,
  url: t.request.url,
  headers: t.request.headers || {},
  body: t.request.body || null,
  assertions: t.assertions.map(a => ({
    type: a.type,
    ...a
  }))
})), null, 2)};

// Helper functions
function substituteVariables(str, vars) {
  if (!str) return str;
  return str.replace(/\\{\\{([^}]+)\\}\\}/g, (match, varName) => {
    return vars[varName.trim()] || match;
  });
}

function makeRequest(test, vars) {
  return new Promise((resolve, reject) => {
    let url = substituteVariables(test.url, vars);
    if (config.baseUrl) {
      url = url.replace(/^https?:\\/\\/[^\\/]+/, config.baseUrl);
    }

    const urlObj = new URL(url);
    const isHttps = urlObj.protocol === 'https:';
    const client = isHttps ? https : http;

    const headers = {};
    for (const [key, value] of Object.entries(test.headers)) {
      headers[substituteVariables(key, vars)] = substituteVariables(value, vars);
    }

    const options = {
      hostname: urlObj.hostname,
      port: urlObj.port || (isHttps ? 443 : 80),
      path: urlObj.pathname + urlObj.search,
      method: test.method,
      headers
    };

    const startTime = Date.now();
    const req = client.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        resolve({
          status: res.statusCode,
          headers: res.headers,
          data,
          duration: Date.now() - startTime
        });
      });
    });

    req.on('error', reject);

    if (test.body) {
      req.write(substituteVariables(test.body, vars));
    }

    req.end();
  });
}

// Run tests
async function runTests() {
  console.log(\`Running \${tests.length} API tests...\\n\`);

  let passed = 0;
  let failed = 0;
  const results = [];

  for (let i = 0; i < tests.length; i++) {
    const test = tests[i];
    process.stdout.write(\`Test \${i + 1}/\${tests.length}: \${test.name}... \`);

    try {
      const response = await makeRequest(test, config.variables);
      const success = response.status >= 200 && response.status < 300;

      if (success) {
        console.log(\`\\x1b[32mPASSED\\x1b[0m (\${response.status}, \${response.duration}ms)\`);
        passed++;
      } else {
        console.log(\`\\x1b[31mFAILED\\x1b[0m (\${response.status})\`);
        failed++;
      }

      results.push({
        name: test.name,
        passed: success,
        status: response.status,
        duration: response.duration
      });
    } catch (error) {
      console.log(\`\\x1b[31mERROR\\x1b[0m (\${error.message})\`);
      failed++;
      results.push({
        name: test.name,
        passed: false,
        error: error.message
      });
    }
  }

  // Summary
  console.log(\`\\n=========================================\`);
  console.log(\`Test Results: \${passed} passed, \${failed} failed\`);

  if (failed === 0) {
    console.log(\`\\x1b[32mAll tests passed!\\x1b[0m\`);
    process.exit(0);
  } else {
    console.log(\`\\x1b[31mSome tests failed!\\x1b[0m\`);
    process.exit(1);
  }
}

runTests().catch(err => {
  console.error('Test runner failed:', err);
  process.exit(1);
});
`;

  return script;
}

// Helper for GitHub Actions
function generateShellTestCommands(tests: TestCase[], indent: string, useMatrix: boolean): string {
  let commands = '';

  tests.forEach((test, index) => {
    const url = useMatrix
      ? test.request.url.replace(/^https?:\/\/[^\/]+/, '${{ matrix.environment }}')
      : test.request.url;

    commands += `${indent}echo "Test ${index + 1}: ${test.name}"\n`;
    commands += `${indent}curl -s -f -X ${test.request.method} "${url}"`;

    if (test.request.headers) {
      for (const [key, value] of Object.entries(test.request.headers)) {
        commands += ` -H "${key}: ${value}"`;
      }
    }

    if (test.request.body) {
      commands += ` -d '${test.request.body.replace(/'/g, "'\\''")}'`;
    }

    commands += ` || exit 1\n`;
  });

  return commands;
}

// Generate curl command for a single test
export function generateCurlCommand(test: TestCase): string {
  let cmd = `curl -X ${test.request.method} "${test.request.url}"`;

  if (test.request.headers) {
    for (const [key, value] of Object.entries(test.request.headers)) {
      cmd += ` \\\n  -H "${key}: ${value}"`;
    }
  }

  if (test.request.body) {
    cmd += ` \\\n  -d '${test.request.body.replace(/'/g, "'\\''")}'`;
  }

  return cmd;
}

// Generate environment matrix configuration
export function generateEnvironmentMatrix(environments: TestEnvironment[]): string {
  return JSON.stringify(environments, null, 2);
}
